Notes for Deep Dive 45.
ipfs/camp pull request #160
Opened 2019-07-08 16:11 UTC by jkarni

2019-07-08 17:38 UTC, alanshaw approved these changes

2019-07-08 17:38 UTC, alanshaw commented on DEEP_DIVES/45-building-dynamic-p2p-applications.md
> +Using
Using...?

2019-07-09 05:53 UTC, avras requested changes
The last team member is actually @guillemcordoba and not @glouvigny. I made a mistake in the slide of our deep dive presentation

2019-07-09 08:56 UTC, avras approved these changes

2019-07-09 09:46 UTC, merged