Add links to demo and slide deck for Core Course C
ipfs/camp pull request #178
Opened 2019-08-19 20:58 UTC by terichadbourne

2019-08-21 14:18 UTC, lidel requested changes
I've created PDF version to remove reliance on proprietary Google Docs:
[IPFS.Camp.2019.-.Core.Course.C.-.Slide.Deck.pdf](https://github.com/ipfs/camp/files/3525750/IPFS.Camp.2019.-.Core.Course.C.-.Slide.Deck.pdf)

See also: https://github.com/ipfs-shipyard/camp-course-c-demo/pull/1

2019-08-21 14:18 UTC, lidel commented on CORE_AND_ELECTIVE_COURSES/CORE_COURSE_C/README.md
> +- View the [slide deck](https://docs.google.com/presentation/d/1cbJD5j_jRpm3yJiE6hLIOzMn8iMhvzyci7Ut3NLjqxs/edit?usp=sharing)
```suggestion
- View the slide deck: [PDF](https://github.com/ipfs/camp/files/3525750/IPFS.Camp.2019.-.Core.Course.C.-.Slide.Deck.pdf), [Google Docs](https://docs.google.com/presentation/d/1cbJD5j_jRpm3yJiE6hLIOzMn8iMhvzyci7Ut3NLjqxs/edit?usp=sharing)
```

2019-08-21 14:18 UTC, lidel commented on CORE_AND_ELECTIVE_COURSES/CORE_COURSE_C/README.md
> +- Try the [demo](https://github.com/ipfs-shipyard/camp-course-c-demo)
```suggestion
- Try running the [demo app](https://github.com/ipfs-shipyard/camp-course-c-demo)
```

2019-08-21 14:32 UTC, lidel approved these changes

2019-08-22 19:28 UTC, terichadbourne commented
@daviddias or someone with super admin powers, can you please merge this one?

2019-08-22 20:05 UTC, lidel commented
@jessicaschilling  ?

2019-08-22 20:06 UTC, merged